### ISSUE TITLE
Invalid JSON RPC response when loading Web3Container

### ISSUE THREAD

**Issue by lightswarm124** [adrianmcli/truffle-next#22]
Both accounts.js and dapp.js pages show this response in the browser console.

*Alert*
Failed to load web3, accounts, or contract. Check console for details.
*Alert*

Error: Invalid JSON RPC response: ""
Stack trace:
InvalidResponse@http://localhost:3000/_next/1518114906012/page/dapp.js:54937:16
module.exports</HttpProvider.prototype.send/request.onreadystatechange@http://localhost:3000/_next/1518114906012/page/dapp.js:63881:25

**Comment by adrianmcli** [comment]
I am unable to reproduce, can you check the following?

1. Make sure that `client/lib/contracts` exists and that `SimpleStorage.json` is inside that symlink.

2. Try running `migrate --reset` with Truffle to reset the deployment of the contracts.

3. Try running in an incognito browser window, just in case MetaMask is doing something funky.

**Comment by lightswarm124** [comment]
I found the issue. "getWeb3.js" file in the Lib folder was setting port to 9545. I toggled it 8545 (what my ganache instance was using) and it worked
