### ISSUE TITLE
Thoughts on utilizing Truffle's Drizzle Web3 state management package

### ISSUE THREAD

**Issue by lightswarm124** [adrianmcli/truffle-next#24]
I'm reviewing through the [repository](https://github.com/trufflesuite/drizzle) Truffle recently released a redux state manager tool that helps save accounts, contracts, transactions and web3 instances. There's also other React-specific components that are similar to what you've got

**Comment by adrianmcli** [comment]
Thanks for letting me know about this. I'll look into it.

**Comment by adrianmcli** [comment]
Hmm interesting. I think Drizzle can definitely be useful, but I am not yet convinced that we should force people to use this state management library (unless it starts becoming a standard). There's something to be said for having just simple React components and passing objects down.

**Comment by wesharehoodies** [comment]
With the new React (16.3) context API you can avoid "Prop drilling".

**Comment by adrianmcli** [comment]
@wesharehoodies Yes, I'm aware of the new context API. But I'm a bit against implementing new API unless it has really settled into the consciousness of beginner React developers.

Thanks for the mention though, might implement later on if the situation sees fit.

**Comment by adrianmcli** [comment]
I have bumped the React version to 16.3, but I don't think we will be integrating anything from Drizzle at this time, even though it looks quite awesome. Will be closing for now until this becomes more relevant again.
