### ISSUE TITLE
Component to track and automate contract deployment?

### ISSUE THREAD

**Issue by lightswarm124** [adrianmcli/truffle-next#25]
I've been playing with the various libraries to deploy contracts through buttons on web apps. Seems like a concise module to help deploy and load each contract would be useful to work with. 

Thoughts?

**Comment by adrianmcli** [comment]
@lightswarm124 hey thanks for the suggestion, do you have a link to these libraries that you are mentioning?

**Comment by adrianmcli** [comment]
I've taken a look at Drizzle and found the overall concept quite interesting. I'm not sure that I like their API right now, but I'm open to changing my mind. It seems like a Redux-like store is enforced, and I don't really like that. Perhaps if it gets more traction, we can consider integrating something like it again.

That being said, something more modular might make sense. I'll have to dig further into Drizzle to see how they do that. And hopefully maybe we can build something that can have the same benefit without requiring the whole Redux-like paradigm.

**Comment by adrianmcli** [comment]
Closed due to inactivity.
