### ISSUE TITLE
Error: SimpleStorage has not been deployed to detected network (network/artifact mismatch)

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [adrianmcli/truffle-next#27]
Thanks for this Adrian.

btw I get an error when I click go to dapp.

Error: SimpleStorage has not been deployed to detected network (network/artifact mismatch)

any clue?

**Comment by adrianmcli** [comment]
I just tested this again and it seems to work just fine. I suspect it is a problem on your end. Ensure that you have the latest version of Truffle and that you are connecting to the correct network.
