### ISSUE TITLE
code?id=105&subid=51824_5680_:1 Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by hskang9** [adrianmcli/truffle-next#31]
The error keep showing for not finding jQuery. Should I add jquery package to the project?

**Comment by adrianmcli** [comment]
Can you provide the steps to replicate this error?

**Comment by adrianmcli** [comment]
Closed due to inactivity. This sounds like an environment problem, we do not use jQuery in our project.
