### ISSUE TITLE
My Dapp and My Accounts pages are stuck

### ISSUE THREAD

**Issue by tanmaybhardwaj** [adrianmcli/truffle-next#34]
I downloaded the repository as per the instructions, ran truffle, compiled and deployed the contracts.
Successfully ran npm run dev command and rendered index.js.
But account.js and dapp.js are simply stuck on 'Loading Accounts Page...' and never display anything else when clicked on their respective links on index.js.

**Comment by adrianmcli** [comment]
Thanks for reporting, I'll look into this. In the mean time, can I ask whether you are using a browser with MetaMask activated? If so, try it with MetaMask deactivated.

**Comment by adrianmcli** [comment]
I just tested it right now, and it seems to be working.

**Comment by tanmaybhardwaj** [comment]
Hi, thanks for your quick reply. I just tested the app with Metamask deactivated and it rendered the accounts from truffle and both pages successfully.
Can you please suggest how can I make it work with Metamask.

**Comment by adrianmcli** [comment]
You'd have to open MetaMask, and add `http://localhost:9545` as the network you want to use.

**Comment by tanmaybhardwaj** [comment]
Thanks, able to access Metamask accounts as well after adding http://localhost:9545 as the network.
