### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by schmijos** [adrianmcli/truffle-next#36]
Currently your box (I guess especially the Next.js client) cannot be used freely because people would have to ask you for permission. Would you mind adding a license to clear up the situation?

**Comment by adrianmcli** [comment]
We had the same discussion on the React one: https://github.com/adrianmcli/truffle-react/issues/6

MIT is already specified in the `package.json` of this project as well. If this is insufficient for your needs, I can add a `LICENSE.md`.

**Comment by schmijos** [comment]
Ah, I didn't look there. Thank you for mentioning. This is technically sufficient, but nevertheless a `LICENSE.md` would be nice 😎
